version: "3.8"

services:
  web:
    image: ghcr.io/bart0llo/golink-web:latest
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:4000/api
      NEXT_PUBLIC_REDIRECT_URL: http://localhost:3000
      NEXT_PUBLIC_ANALYTICS_ID: 192229ef
    ports:
      - "3000:3000"
    restart: always

  server:
    image: ghcr.io/bart0llo/golink-server:latest
    environment:
      DATABASE_URL: postgresql://root:password@localhost:5432/golink?schema=public
      API_PREFIX: api
    ports:
      - "4000:4000"
    restart: always
